package tlsrecord

import (
	"bytes"
	"encoding/hex"
	"errors"
	"testing"
)

func mustHex(t testing.TB, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

// These values were generated by tools/tlsrecordvector in Actions at
// SOURCE_SHA 65184f80bde05240071fd8954a15db4118d59609. That command does not
// import internal/tlsrecord and implements WIRE_SPEC directly from primitives.
func TestIndependentReferenceKeys(t *testing.T) {
	wantContext := mustHex(t, "0f3fbaf77820046d23cf3ffb12c005e2cee079172d302d8e8f5250bdd8d44b42")
	context, err := ExporterContextHash(1, testNonce(), []byte("tunnel-vector-01"), 1500, 1600)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(context[:], wantContext) {
		t.Fatalf("context hash = %x, want %x", context, wantContext)
	}

	pair, err := DeriveKeys(testMaster(), testNonce())
	if err != nil {
		t.Fatal(err)
	}
	checks := []struct {
		name string
		got  []byte
		want string
	}{
		{"c2s-aead", pair.C2S.AEADKey[:], "d0294fa835aad90edac241793a9e5fc129c98de34676529ee7620ec02ade7a99"},
		{"c2s-iv", pair.C2S.IV[:], "1a66f526ac13361d3cd0ddae"},
		{"c2s-hp", pair.C2S.HPKey[:], "ba46fc4a618d2356293ccc9c5dbd173327e58500f18b507c5d0bdf74953d54e7"},
		{"s2c-aead", pair.S2C.AEADKey[:], "d5af057aa4a79572781dac05cf2375b06054da90c796afdd057a74b94666cac6"},
		{"s2c-iv", pair.S2C.IV[:], "dab52a4a67d5bbc1f26e5633"},
		{"s2c-hp", pair.S2C.HPKey[:], "edce954181ba344fc3f48f5ebab5b21cf09470f9504fe0ab7e3f06031a131df0"},
	}
	for _, tc := range checks {
		t.Run(tc.name, func(t *testing.T) {
			want := mustHex(t, tc.want)
			if !bytes.Equal(tc.got, want) {
				t.Fatalf("got %x, want %x", tc.got, want)
			}
		})
	}
}

func TestIndependentReferenceWireBytes(t *testing.T) {
	keys := testKeys(t)
	sealer, err := NewSealer(keys, MaxWireLen)
	if err != nil {
		t.Fatal(err)
	}
	opener, err := NewOpener(keys, MaxWireLen)
	if err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name    string
		pn      uint64
		payload []byte
		wireHex string
	}{
		{"pn0-empty", 0, nil, "170303001a027cfaf5ec687ea1e7c8481a7c8ab1526ab9d42562c1b9abd747"},
		{"pn1-ascii", 1, []byte("hello"), "170303001ffca72f89c226531226e48a907f48bc3fae1c41b701493abe800e1b42214bca"},
		{"pn-cross32", (1 << 32) + 1, []byte{0x00, 0xff, 0x10, 0x20}, "170303001e71e42fe21689ab6be698afeddf5a22f4a3f8b127d7bf5d2e3ed5bebb2728"},
		{"pn-max-minus1", ^uint64(0) - 1, []byte("near-max"), "17030300220314e9e73e2b4fc92d133412a72a94f2e46fb533b210d076ae944c7869b45ac3d4de"},
		{"pn-max", ^uint64(0), nil, "170303001a4fbf6f100e33581102d306bffc66f3c304b4fda4dda42c28233e"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			wantWire := mustHex(t, tc.wireHex)
			gotWire, err := sealRecord(keys, sealer.aead, sealer.maxBody, tc.pn, KindLINK, tc.payload, 0)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(gotWire, wantWire) {
				t.Fatalf("wire = %x, want %x", gotWire, wantWire)
			}
			again, err := sealRecord(keys, sealer.aead, sealer.maxBody, tc.pn, KindLINK, tc.payload, 0)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(again, wantWire) {
				t.Fatal("same PN/key/plaintext did not reproduce immutable wire bytes")
			}
			record, err := opener.OpenRecord(wantWire)
			if err != nil {
				t.Fatal(err)
			}
			if record.PN != tc.pn || !bytes.Equal(record.Payload, tc.payload) {
				t.Fatalf("opened pn=%d payload=%x", record.PN, record.Payload)
			}
		})
	}
}

func TestDeepReorderHasNoReceiveWindow(t *testing.T) {
	keys := testKeys(t)
	sealer, _ := NewSealer(keys, MaxWireLen)
	decoder, _ := NewDecoder(keys, MaxWireLen)

	farPN := uint64((1 << 32) + 1)
	far, err := sealRecord(keys, sealer.aead, sealer.maxBody, farPN, KindLINK, []byte("far"), 0)
	if err != nil {
		t.Fatal(err)
	}
	early, err := sealRecord(keys, sealer.aead, sealer.maxBody, 0, KindLINK, []byte("early"), 0)
	if err != nil {
		t.Fatal(err)
	}

	got := decoder.OpenPayload(far)
	if len(got) != 1 || got[0].Err != nil || got[0].PN != farPN {
		t.Fatalf("far result = %#v", got)
	}
	got = decoder.OpenPayload(early)
	if len(got) != 1 || got[0].Err != nil || got[0].PN != 0 || string(got[0].Payload) != "early" {
		t.Fatalf("late early-PN result = %#v", got)
	}
	if decoder.Stats().Late != 1 {
		t.Fatalf("late = %d, want 1", decoder.Stats().Late)
	}
}

func TestAuthenticationFailureDoesNotUpdateRecentPN(t *testing.T) {
	keys := testKeys(t)
	sealer, _ := NewSealer(keys, MaxWireLen)
	decoder, _ := NewDecoder(keys, MaxWireLen)
	valid, _, err := sealer.Seal([]byte("valid-after-failure"))
	if err != nil {
		t.Fatal(err)
	}
	corrupt := append([]byte(nil), valid...)
	corrupt[len(corrupt)-1] ^= 0x01

	got := decoder.OpenPayload(corrupt)
	if len(got) != 1 || !errors.Is(got[0].Err, ErrAuthentication) {
		t.Fatalf("corrupt result = %#v", got)
	}
	got = decoder.OpenPayload(valid)
	if len(got) != 1 || got[0].Err != nil || got[0].PN != 0 {
		t.Fatalf("valid result after auth failure = %#v", got)
	}
	if decoder.Stats().Duplicates != 0 || decoder.Stats().Delivered != 1 {
		t.Fatalf("stats = %#v", decoder.Stats())
	}
}

func TestExplicitShortPayloadsAreRejected(t *testing.T) {
	keys := testKeys(t)
	decoder, _ := NewDecoder(keys, MaxWireLen)
	for n := 0; n < OuterHeaderLen; n++ {
		got := decoder.OpenPayload(make([]byte, n))
		if n == 0 {
			if len(got) != 0 {
				t.Fatalf("empty payload result = %#v", got)
			}
			continue
		}
		if len(got) != 1 || !errors.Is(got[0].Err, ErrInvalidLength) {
			t.Fatalf("short length %d result = %#v", n, got)
		}
	}
}
