param(
    [Parameter(Mandatory=$true)][string]$BinDir,
    [Parameter(Mandatory=$true)][string]$LinuxAssets,
    [Parameter(Mandatory=$true)][ValidateSet(1,4)][int]$Lanes,
    [Parameter(Mandatory=$true)][ValidateSet('off','20:20')][string]$FEC,
    [int]$ConnectionMTU=1420,
    [int]$DurationSec=300,
    [int]$RateBps=2000000,
    [int]$LossPct=15,
    [int]$RotateEverySec=90,
    [Parameter(Mandatory=$true)][string]$LogDir
)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
if($ConnectionMTU-le 0-or$DurationSec-le 0-or$RateBps-le 0-or$LossPct-lt 0-or$LossPct-ge 100-or$RotateEverySec-lt 10){throw 'invalid soak parameters'}
New-Item -ItemType Directory -Force -Path $LogDir|Out-Null
$BinDir=(Resolve-Path $BinDir).Path;$LinuxAssets=(Resolve-Path $LinuxAssets).Path;$LogDir=(Resolve-Path $LogDir).Path;$repo=(Resolve-Path(Join-Path $PSScriptRoot '..')).Path
$rebindSource=Join-Path $repo 'scripts\windows_tun_rebind.ps1';if(-not(Test-Path -LiteralPath $rebindSource)){throw 'current-HEAD windows_tun_rebind.ps1 is missing'};Copy-Item -LiteralPath $rebindSource -Destination(Join-Path $BinDir 'windows_tun_rebind.ps1') -Force
$adapterName='WBDSoak';$qualifier=Join-Path $BinDir 'wbd-windows-qualify.exe';$profilePath=Join-Path $LogDir 'wbd-soak-profile.json';$readyFile=Join-Path $LogDir 'qualifier.ready';$stopFile=Join-Path $LogDir 'stop.qualifier';$qualOut=Join-Path $LogDir 'qualifier.stdout.log';$qualErr=Join-Path $LogDir 'qualifier.stderr.log';$serverStop=Join-Path $LogDir 'stop.server'
function Wait-Path([string]$Path,[int]$Seconds,[System.Diagnostics.Process]$Process,[string]$Label){$deadline=[DateTime]::UtcNow.AddSeconds($Seconds);while([DateTime]::UtcNow-lt$deadline){if(Test-Path -LiteralPath $Path){return};if($null-ne$Process-and$Process.HasExited){$tail=if(Test-Path -LiteralPath $qualErr){(Get-Content -LiteralPath $qualErr -Tail 100)-join"`n"}else{'<no stderr>'};throw "$Label exited before readiness exit=$($Process.ExitCode)`n$tail"};Start-Sleep -Milliseconds 100};throw "$Label readiness timeout waiting for $Path"}
function WslPath([string]$Path){$full=[System.IO.Path]::GetFullPath($Path);$root=[System.IO.Path]::GetPathRoot($full);if([string]::IsNullOrWhiteSpace($root)-or$root.Length-lt3){throw "unsupported Windows path for WSL: $Path"};$drive=$root.Substring(0,1).ToLowerInvariant();$rest=$full.Substring($root.Length).Replace([char]92,'/');return "/mnt/$drive/$rest"}
function Start-WslServer([string[]]$Arguments){$psi=[System.Diagnostics.ProcessStartInfo]::new();$psi.FileName='wsl.exe';$psi.UseShellExecute=$false;foreach($arg in $Arguments){[void]$psi.ArgumentList.Add([string]$arg)};$proc=[System.Diagnostics.Process]::new();$proc.StartInfo=$psi;if(-not$proc.Start()){throw 'failed to start WSL soak server'};return $proc}
$budgetJson=& go run(Join-Path $repo '.github\scripts\mtu_budget.go') -connection-mtu $ConnectionMTU -fec $FEC;if($LASTEXITCODE){throw 'MTU budget probe failed'}
$budget=$budgetJson|ConvertFrom-Json;$innerMTU=[int]$budget.InnerMTU;$linkMTU=[int]$budget.LinkPlaintextMTU;$budget|ConvertTo-Json -Depth 5|Set-Content -LiteralPath(Join-Path $LogDir 'mtu-budget.json') -Encoding utf8
Write-Output "WBD_WINTUN_SOAK_MTU_DERIVED connection=$ConnectionMTU fec=$FEC link=$linkMTU inner=$innerMTU"
[string]$distro=[string](@(& wsl.exe -l -q|ForEach-Object{$_.Replace([string][char]0,'').Trim()}|Where-Object{$_})|Select-Object -First 1);$distro=$distro.Replace([string][char]0,'').Trim();if(-not$distro){throw 'no WSL distribution'}
& wsl.exe -d $distro -- true;if($LASTEXITCODE){throw "selected WSL distribution is unavailable: $distro"};Write-Output "WBD_WSL_DISTRO_SELECTED distro=$distro"
$wslAssets=WslPath $LinuxAssets;$wslLog=WslPath $LogDir;$wslServerScript=WslPath(Join-Path $repo 'scripts\wsl_wintun_lane_soak_server.sh')
[string[]]$serverArgs=@('-d',$distro,'--','sudo','bash',$wslServerScript,$wslAssets,$wslLog,"$innerMTU","$ConnectionMTU","$Lanes","$LossPct")
$server=Start-WslServer $serverArgs
$qual=$null;$load=$null;$clock=$null;$rotations=@();$lastQualifierLine=0;$serverStopped=$false;$qualifierStopped=$false
function Capture-RotationLines{if(-not(Test-Path -LiteralPath $qualOut)-or$null-eq$clock){return};$lines=@(Get-Content -LiteralPath $qualOut -ErrorAction SilentlyContinue);for($i=$script:lastQualifierLine;$i-lt$lines.Count;$i++){$line=[string]$lines[$i];if($line-match'WBD_LANE_ROTATION_PASS\s+lane=(\d+)'){$script:rotations+=[ordered]@{ordinal=$script:rotations.Count+1;lane=[int]$Matches[1];observed_commit_sec=[Math]::Round($script:clock.Elapsed.TotalSeconds,3);raw=$line.Trim()}}};$script:lastQualifierLine=$lines.Count}
try{
 $serverReady=Join-Path $LogDir 'server-ready.json';$deadline=[DateTime]::UtcNow.AddSeconds(60);while(-not(Test-Path -LiteralPath $serverReady)){if($server.HasExited){throw "WSL server exited before readiness exit=$($server.ExitCode)"};if([DateTime]::UtcNow-ge$deadline){throw 'WSL readiness timeout'};Start-Sleep -Milliseconds 200}
 $serverInfo=Get-Content -LiteralPath $serverReady -Raw|ConvertFrom-Json;$serverIP=[string]$serverInfo.server_ip;$echoIP=[string]$serverInfo.echo_ip;$echoPort=[int]$serverInfo.echo_port
 if([int]$serverInfo.inner_mtu-ne$innerMTU-or[int]$serverInfo.connection_mtu-ne$ConnectionMTU){throw 'server MTU budget does not match local pathmtu derivation'}
 $underlayLines=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File(Join-Path $BinDir 'windows_faketcp_underlay.ps1') -RemoteIPAddress $serverIP;if($LASTEXITCODE){throw 'pre-connect underlay discovery failed'}
 $underlayJSON=$underlayLines|Where-Object{$_-match'^\{'}|Select-Object -First 1;if(-not$underlayJSON){throw 'underlay discovery returned no JSON'};$underlay=$underlayJSON|ConvertFrom-Json
 if([string]$underlay.packet_device-notmatch'^\\Device\\NPF_\{.+\}$'){throw 'underlay is not an Npcap NPF device'};$underlay|ConvertTo-Json -Depth 6|Set-Content -LiteralPath(Join-Path $LogDir 'underlay.json') -Encoding utf8
 Write-Output "WBD_WINDOWS_OUTER_CARRIER_READY remote=$serverIP packet_device=$($underlay.packet_device) npcap=real"
 $profile=[ordered]@{server_ip=$serverIP;server_port=40000;server_name='target.example';route_key='WBD_REALITY_ROUTE_KEY_0123456789abcdef';username='solo';password='shared-password';verify_server=$false;fec=$FEC;if_name=$adapterName;mtu=$ConnectionMTU;route_mode='Full';dns_mode='System';lanes=$Lanes;idle_timeout=0;lane_rotation_min_seconds=$RotateEverySec;lane_rotation_max_seconds=$RotateEverySec}
 $profile|ConvertTo-Json -Depth 6|Set-Content -LiteralPath $profilePath -Encoding utf8;Remove-Item -LiteralPath $readyFile,$stopFile -Force -ErrorAction SilentlyContinue
 [string[]]$qualArgs=@('-profile',[string]$profilePath,'-run-for','0','-stop-file',[string]$stopFile,'-ready-file',[string]$readyFile)
 $qual=Start-Process -FilePath $qualifier -ArgumentList $qualArgs -RedirectStandardOutput $qualOut -RedirectStandardError $qualErr -PassThru -NoNewWindow
 Wait-Path $readyFile 120 $qual 'Windows production controller';$clock=[Diagnostics.Stopwatch]::StartNew();Capture-RotationLines
 $lease=Get-NetIPAddress -InterfaceAlias $adapterName -AddressFamily IPv4 -ErrorAction Stop|Where-Object{[string]$_.AddressState-eq'Preferred'}|Select-Object -First 1;if(-not$lease){throw 'Wintun lease is missing after controller readiness'}
 $leaseIP=[string]$lease.IPAddress;$leaseCIDR="$leaseIP/$([int]$lease.PrefixLength)";$beforeStats=Get-NetAdapterStatistics -Name $adapterName
 $qualStdout=Get-Content -LiteralPath $qualOut -Raw;$qualStderr=if(Test-Path -LiteralPath $qualErr){Get-Content -LiteralPath $qualErr -Raw}else{''};$qualText=$qualStdout+"`n"+$qualStderr;if($qualText-notmatch'WBD_FAKETCP_WINDOWS_RAW_SYNACK_RX'){throw 'real Npcap raw SYN/SYNACK proof marker missing'};if($qualStdout-notmatch'WBD_WINDOWS_QUALIFY_CONNECTED'){throw 'production controller connected marker missing'}
 Write-Output "WBD_WINDOWS_PRODUCTION_CONTROLLER_READY lease=$leaseCIDR lanes=$Lanes fec=$FEC rotation=${RotateEverySec}/${RotateEverySec}"
 $smoke=[System.Net.Sockets.UdpClient]::new([System.Net.IPEndPoint]::new([System.Net.IPAddress]::Parse($leaseIP),0));try{$smoke.Client.ReceiveTimeout=15000;$payload=[Text.Encoding]::UTF8.GetBytes("WBD_TUN_FULL_CHAIN_SMOKE_$PID");[void]$smoke.Send($payload,$payload.Length,$echoIP,$echoPort);$peer=[Net.IPEndPoint]::new([Net.IPAddress]::Any,0);$reply=$smoke.Receive([ref]$peer);if(-not[Linq.Enumerable]::SequenceEqual([byte[]]$payload,[byte[]]$reply)){throw 'TUN smoke mismatch'}}finally{$smoke.Dispose()}
 Write-Output "WBD_WINDOWS_WINTUN_FULL_CHAIN_SMOKE_PASS lease=$leaseIP target=${echoIP}:$echoPort"
 $loadResult=Join-Path $LogDir 'load-result.json';[string[]]$loadArgs=@([string](Join-Path $repo '.github\scripts\windows_game_load.py'),'--target',"${echoIP}:$echoPort",'--bind',[string]$leaseIP,'--duration',"$DurationSec",'--rate-bps',"$RateBps",'--payload-bytes','1000','--out',[string]$loadResult)
 $load=Start-Process -FilePath 'python' -ArgumentList $loadArgs -RedirectStandardOutput(Join-Path $LogDir 'load.stdout.log') -RedirectStandardError(Join-Path $LogDir 'load.stderr.log') -PassThru -NoNewWindow
 while(-not$load.HasExited){if($qual.HasExited){throw "production controller exited during load exit=$($qual.ExitCode)"};Capture-RotationLines;Start-Sleep -Milliseconds 200};Capture-RotationLines;if($load.ExitCode-ne0){throw "inner load exited $($load.ExitCode)"};if(-not(Test-Path -LiteralPath $loadResult)){throw 'inner load did not produce result'}
 $loadStats=Get-Content -LiteralPath $loadResult -Raw|ConvertFrom-Json;if([int64]$loadStats.sent-le0-or[int64]$loadStats.unique_rx-le0){throw 'inner traffic did not traverse the full path'}
 $innerSentBytes=[int64]$loadStats.sent*[int64]$loadStats.payload_bytes;$innerRxBytes=[int64]$loadStats.unique_rx*[int64]$loadStats.payload_bytes;$innerByteLossPct=if($innerSentBytes-gt0){100.0*($innerSentBytes-$innerRxBytes)/$innerSentBytes}else{100.0}
 $afterStats=Get-NetAdapterStatistics -Name $adapterName -ErrorAction Stop;$txBytes=[uint64]$afterStats.SentBytes-[uint64]$beforeStats.SentBytes;$rxBytes=[uint64]$afterStats.ReceivedBytes-[uint64]$beforeStats.ReceivedBytes
 New-Item -ItemType File -Force -Path $stopFile|Out-Null;if(-not$qual.WaitForExit(60000)){throw 'production controller did not stop cleanly'};$qualifierStopped=$true;Capture-RotationLines;if($qual.ExitCode-ne0){throw "production controller cleanup exited $($qual.ExitCode)"};$qualText=Get-Content -LiteralPath $qualOut -Raw;if($qualText-notmatch'WBD_WINDOWS_QUALIFY_CLEANUP_PASS'){throw 'production controller cleanup marker missing'}
 New-Item -ItemType File -Force -Path $serverStop|Out-Null;if(-not$server.WaitForExit(30000)){throw 'WSL server did not stop cleanly'};$serverStopped=$true;if($server.ExitCode-ne0){throw "WSL server exited $($server.ExitCode)"}
 if($rotations.Count-lt3){throw "automatic lane rotation produced only $($rotations.Count) commits"};$times=@($rotations|ForEach-Object{[double]$_.observed_commit_sec});foreach($epoch in @(90,180,270)){$near=@($times|Where-Object{[Math]::Abs($_-$epoch)-le30});if($near.Count-eq0){throw "no automatic lane rotation commit observed near ${epoch}s"}}
 $fecRows=@();foreach($path in @($qualOut,(Join-Path $LogDir 'link-server.log'))){if(-not(Test-Path -LiteralPath $path)){continue};foreach($line in (Get-Content -LiteralPath $path)){if($line-match'^WBD_LINK_FEC_DIAG\s+(\{.*\})$'){try{$fecRows+=($Matches[1]|ConvertFrom-Json)}catch{throw "invalid FEC diagnostic JSON in $path"}}}}
 $fecPeak=0;$fecCurrent=0;$fecMaxBlocks=0;$fecPeakRetired=0;$fecPeakRetiredIncomplete=0;$fecPeakRetiredMissing=0;$fecPressureRetire=[uint64]0;$fecRecoveryExpire=[uint64]0;$fecRecoveryExpiredIncomplete=[uint64]0;$fecLast=$null
 if($FEC-eq'20:20'){if($fecRows.Count-eq0){throw 'FEC diagnostics missing for FEC-on soak'};foreach($row in $fecRows){$maxBlocks=[int]$row.decoder.max_blocks;if($maxBlocks-ne640){throw "unexpected FEC max_blocks=$maxBlocks"};$fecMaxBlocks=$maxBlocks;$fecPeak=[Math]::Max($fecPeak,[int]$row.peak_in_flight);$fecPeakRetired=[Math]::Max($fecPeakRetired,[int]$row.peak_retired);$fecPeakRetiredIncomplete=[Math]::Max($fecPeakRetiredIncomplete,[int]$row.peak_retired_incomplete);$fecPeakRetiredMissing=[Math]::Max($fecPeakRetiredMissing,[int]$row.peak_retired_missing_sources);$fecPressureRetire=[Math]::Max($fecPressureRetire,[uint64]$row.pressure_retire_events);$fecRecoveryExpire=[Math]::Max($fecRecoveryExpire,[uint64]$row.recovery.expire_events);$fecRecoveryExpiredIncomplete=[Math]::Max($fecRecoveryExpiredIncomplete,[uint64]$row.recovery.expired_incomplete)};$fecLast=$fecRows[-1];$fecCurrent=[int]$fecLast.decoder.in_flight;if($fecPeak-ge640){throw "FEC decoder saturated peak_in_flight=$fecPeak max_blocks=640"}}elseif($fecRows.Count-ne0){throw 'FEC-off soak unexpectedly emitted FEC decoder diagnostics'}
 $fecSaturation=if($fecMaxBlocks-gt0){[Math]::Round(100.0*$fecPeak/$fecMaxBlocks,4)}else{0.0}
 $pressureCurrent=0;$pressurePeak=0;$pressureSamples=0;$pressureCapacity=0;$pressureEvents=0;$pressureWaitEvents=0;$pressureResumeEvents=0;$pressureMaxOutstanding=0
 foreach($line in (Get-Content -LiteralPath $qualOut)){if($line-match'^WBD_FAKETCP_PRESSURE\s+role=client\s+pending=(\d+)\s+peak_pending=(\d+)\s+capacity=(\d+)$'){$pressureSamples++;$pending=[int]$Matches[1];$peak=[int]$Matches[2];$capacity=[int]$Matches[3];if($capacity-ne4096){throw "unexpected FakeTCP outstanding capacity=$capacity"};$pressureCapacity=$capacity;$pressureCurrent=$pending;$pressurePeak=[Math]::Max($pressurePeak,[Math]::Max($pending,$peak))}elseif($line-match'^WBD_FAKETCP_OUTSTANDING_PRESSURE\s+role=client\s+pending=(\d+)\s+limit=(\d+)\s+action=wait$'){$pressureEvents++;$pressureWaitEvents++;$outstanding=[int]$Matches[1];$limit=[int]$Matches[2];if($limit-ne4096){throw "unexpected FakeTCP pressure limit=$limit"};$pressureMaxOutstanding=[Math]::Max($pressureMaxOutstanding,$outstanding)}elseif($line-match'^WBD_FAKETCP_OUTSTANDING_PRESSURE\s+role=client\s+limit=(\d+)\s+action=resumed$'){$pressureEvents++;$pressureResumeEvents++;$limit=[int]$Matches[1];if($limit-ne4096){throw "unexpected FakeTCP pressure limit=$limit"}}}
 if($pressureSamples-eq0){throw 'FakeTCP capacity observability markers missing'};$pressureSaturation=if($pressureCapacity-gt0){[Math]::Round(100.0*$pressurePeak/$pressureCapacity,4)}else{0.0}
 $faketcpStatsSamples=0;$repairEvicted=[uint64]0;$repairEvictedBytes=[uint64]0;$repairMetadataEvicted=[uint64]0
 foreach($line in (Get-Content -LiteralPath $qualOut)){if($line-match'^WBD_FAKETCP_STATS\s+(\{.*\})$'){try{$stat=$Matches[1]|ConvertFrom-Json}catch{throw 'invalid FakeTCP final stats JSON'};if([string]$stat.role-ne'client'){continue};$faketcpStatsSamples++;$repairEvicted+=[uint64]$stat.sender.RepairEvicted;$repairEvictedBytes+=[uint64]$stat.sender.RepairEvictedBytes;$repairMetadataEvicted+=[uint64]$stat.sender.RepairMetadataEvicted}}
 if($faketcpStatsSamples-eq0){throw 'FakeTCP final stats markers missing after controller cleanup'}
 $networkEnd=Join-Path $LogDir 'network-end.log';if(-not(Test-Path -LiteralPath $networkEnd)){throw 'outer network accounting log missing'};$outerPrePackets=[int64]-1;$outerPreBytes=[int64]-1;$outerPostPackets=[int64]-1;$outerPostBytes=[int64]-1;$tcDropped=[int64]-1;$inNetem=$false
 foreach($line in (Get-Content -LiteralPath $networkEnd)){if($line-match'^\s*(\d+)\s+(\d+)\s+RETURN\s+tcp\b.*\bspt:40000\b'){$outerPrePackets=[int64]$Matches[1];$outerPreBytes=[int64]$Matches[2]};if($line-match'^qdisc netem 30:'){$inNetem=$true;continue};if($inNetem-and$line-match'Sent\s+(\d+)\s+bytes\s+(\d+)\s+pkt\s+\(dropped\s+(\d+)'){$outerPostBytes=[int64]$Matches[1];$outerPostPackets=[int64]$Matches[2];$tcDropped=[int64]$Matches[3];$inNetem=$false}}
 if($outerPrePackets-le0-or$outerPreBytes-le0-or$outerPostPackets-lt0-or$outerPostBytes-lt0){throw "outer accounting missing pre_pkts=$outerPrePackets pre_bytes=$outerPreBytes post_pkts=$outerPostPackets post_bytes=$outerPostBytes"};$outerDroppedPackets=$outerPrePackets-$outerPostPackets;$outerDroppedBytes=$outerPreBytes-$outerPostBytes;if($outerDroppedPackets-lt0-or$outerDroppedBytes-lt0){throw 'outer accounting counters moved backwards'};$outerPacketLoss=100.0*$outerDroppedPackets/$outerPrePackets;$outerByteLoss=100.0*$outerDroppedBytes/$outerPreBytes;if($outerPacketLoss-lt10-or$outerPacketLoss-gt20){throw "outer packet loss out of band: $outerPacketLoss"};if($outerByteLoss-lt10-or$outerByteLoss-gt20){throw "outer byte loss out of band: $outerByteLoss"}
 $scanPattern='panic:|fatal error:|DTLS.*(?:error|fail)|control-plane.*(?:error|fail)|serviceLoop|queue (?:overflow|backpressure)|replay|retransmit|lane.*(?:admission|replacement).*(?:fail|error)|unexpected CLOSE|ticket.*(?:fail|error)|reality.*(?:fail|error)|Npcap.*(?:error|fail)|firewall.*(?:leak|bypass)|WBD_[A-Z0-9_]+_FAIL';$severePattern='panic:|fatal error:|DTLS.*(?:error|fail)|control-plane.*(?:error|fail)|queue overflow|lane.*(?:admission|replacement).*(?:fail|error)|unexpected CLOSE|ticket.*(?:fail|error)|reality.*(?:fail|error)|Npcap.*(?:error|fail)|firewall.*(?:leak|bypass)|WBD_[A-Z0-9_]+_FAIL'
 $logs=Get-ChildItem -LiteralPath $LogDir -File|Where-Object{$_.Name-match'\.(log|txt)$'};$scan=@($logs|Select-String -Pattern $scanPattern -ErrorAction SilentlyContinue);$severe=@($logs|Select-String -Pattern $severePattern -ErrorAction SilentlyContinue);$scan|ForEach-Object{"$($_.Path):$($_.LineNumber):$($_.Line)"}|Set-Content -LiteralPath(Join-Path $LogDir 'error-scan.log') -Encoding utf8;if($severe.Count-gt0){throw "severe error markers found: $($severe.Count)"}
 $summary=[ordered]@{lanes=$Lanes;fec=$FEC;connection_mtu=$ConnectionMTU;link_plaintext_mtu=$linkMTU;inner_mtu=$innerMTU;duration_sec=$DurationSec;rate_bps=$RateBps;configured_random_loss_pct=$LossPct;rotation_profile_min_sec=$RotateEverySec;rotation_profile_max_sec=$RotateEverySec;automatic_rotation_commits=$rotations;lease=$leaseCIDR;underlay=$underlay;npcap_runtime='real';route_mode='Full';topology='windows-client-behind-host-firewall -> Npcap/FakeTCP -> WSL-linux-server-behind-shared-tun-firewall';inner_sent_packets=[int64]$loadStats.sent;inner_sent_bytes=$innerSentBytes;inner_rx_packets=[int64]$loadStats.unique_rx;inner_rx_bytes=$innerRxBytes;inner_packet_loss_pct=[double]$loadStats.inner_loss_pct;inner_byte_loss_pct=$innerByteLossPct;inner_max_rx_gap_ms=[double]$loadStats.max_rx_gap_ms;outer_pre_netem_packets=$outerPrePackets;outer_pre_netem_bytes=$outerPreBytes;outer_post_netem_packets=$outerPostPackets;outer_post_netem_bytes=$outerPostBytes;outer_dropped_packets=$outerDroppedPackets;outer_dropped_bytes=$outerDroppedBytes;outer_packet_loss_pct=$outerPacketLoss;outer_byte_loss_pct=$outerByteLoss;outer_tc_reported_drops=$tcDropped;wintun_tx_bytes=$txBytes;wintun_rx_bytes=$rxBytes;fec_diag_samples=$fecRows.Count;fec_max_blocks=$fecMaxBlocks;fec_current_in_flight=$fecCurrent;fec_peak_in_flight=$fecPeak;fec_saturation_pct=$fecSaturation;fec_peak_retired=$fecPeakRetired;fec_peak_retired_incomplete=$fecPeakRetiredIncomplete;fec_peak_retired_missing_sources=$fecPeakRetiredMissing;fec_pressure_retire_events=$fecPressureRetire;fec_recovery_expire_events=$fecRecoveryExpire;fec_recovery_expired_incomplete=$fecRecoveryExpiredIncomplete;fec_last_diag=$fecLast;faketcp_capacity=$pressureCapacity;faketcp_current_pending=$pressureCurrent;faketcp_peak_pending=$pressurePeak;faketcp_saturation_pct=$pressureSaturation;faketcp_pressure_samples=$pressureSamples;faketcp_outstanding_pressure_events=$pressureEvents;faketcp_outstanding_wait_events=$pressureWaitEvents;faketcp_outstanding_resume_events=$pressureResumeEvents;faketcp_pressure_max_outstanding=$pressureMaxOutstanding;faketcp_final_stats_samples=$faketcpStatsSamples;faketcp_repair_evicted=$repairEvicted;faketcp_repair_evicted_bytes=$repairEvictedBytes;faketcp_repair_metadata_evicted=$repairMetadataEvicted;error_scan_matches=$scan.Count;severe_error_scan_matches=$severe.Count;application_path='windows_udp_socket>wintun>wbd-tun>game-lane>link>dtls>real-npcap-faketcp>linux-shared-tun>udp-echo'}
 $summary|ConvertTo-Json -Depth 14|Set-Content -LiteralPath(Join-Path $LogDir 'summary.json') -Encoding utf8
 Write-Output "WBD_WINDOWS_LINUX_NPCAP_SOAK_PASS lanes=$Lanes fec=$FEC rotations=$($rotations.Count) inner_packet_loss_pct=$([Math]::Round([double]$loadStats.inner_loss_pct,4)) inner_byte_loss_pct=$([Math]::Round($innerByteLossPct,4)) outer_packet_loss_pct=$([Math]::Round($outerPacketLoss,4)) outer_byte_loss_pct=$([Math]::Round($outerByteLoss,4)) fec_peak=$fecPeak fec_saturation_pct=$fecSaturation faketcp_capacity=$pressureCapacity faketcp_current_pending=$pressureCurrent faketcp_peak_pending=$pressurePeak faketcp_saturation_pct=$pressureSaturation faketcp_wait_events=$pressureWaitEvents faketcp_resume_events=$pressureResumeEvents faketcp_repair_evicted=$repairEvicted faketcp_repair_evicted_bytes=$repairEvictedBytes faketcp_repair_metadata_evicted=$repairMetadataEvicted errors=$($scan.Count)"
}finally{if($load-and-not$load.HasExited){try{Stop-Process -Id $load.Id -Force -ErrorAction SilentlyContinue}catch{}};if($qual-and-not$qualifierStopped-and-not$qual.HasExited){try{New-Item -ItemType File -Force -Path $stopFile|Out-Null;[void]$qual.WaitForExit(30000)}catch{};if(-not$qual.HasExited){try{Stop-Process -Id $qual.Id -Force -ErrorAction SilentlyContinue}catch{}}};if(-not$serverStopped){try{New-Item -ItemType File -Force -Path $serverStop|Out-Null}catch{};if($server-and-not$server.HasExited){try{if(-not$server.WaitForExit(10000)){Stop-Process -Id $server.Id -Force -ErrorAction SilentlyContinue}}catch{}}}}
