param(
  [Parameter(Mandatory=$true)][string]$BinDir,
  [Parameter(Mandatory=$true)][string]$LinuxAssets,
  [Parameter(Mandatory=$true)][ValidateSet(1,4)][int]$Lanes,
  [Parameter(Mandatory=$true)][ValidateSet('off','20:20')][string]$FEC,
  [int]$ConnectionMTU=1420,
  [int]$RateBps=2000000,
  [int]$LossPct=15,
  [int]$FirstDurationSec=20,
  [int]$PauseDurationSec=220,
  [int]$SecondDurationSec=60,
  [int]$ServerIdleSec=60,
  [Parameter(Mandatory=$true)][string]$LogDir
)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
New-Item -ItemType Directory -Force -Path $LogDir|Out-Null
$BinDir=(Resolve-Path $BinDir).Path;$LinuxAssets=(Resolve-Path $LinuxAssets).Path;$LogDir=(Resolve-Path $LogDir).Path;$repo=(Resolve-Path(Join-Path $PSScriptRoot '..')).Path
$adapterName='WBDSoak';$qualifier=Join-Path $BinDir 'wbd-windows-qualify.exe';$profilePath=Join-Path $LogDir 'keepalive-profile.json';$readyFile=Join-Path $LogDir 'qualifier.ready';$stopFile=Join-Path $LogDir 'stop.qualifier';$serverStop=Join-Path $LogDir 'stop.server';$qualOut=Join-Path $LogDir 'qualifier.stdout.log';$qualErr=Join-Path $LogDir 'qualifier.stderr.log'
function Wait-Path([string]$Path,[int]$Seconds,[System.Diagnostics.Process]$Process,[string]$Label){$deadline=[DateTime]::UtcNow.AddSeconds($Seconds);while([DateTime]::UtcNow-lt$deadline){if(Test-Path -LiteralPath $Path){return};if($null-ne$Process-and$Process.HasExited){throw "$Label exited before readiness exit=$($Process.ExitCode)"};Start-Sleep -Milliseconds 100};throw "$Label readiness timeout waiting for $Path"}
$budgetJson=& go run(Join-Path $repo '.github\scripts\mtu_budget.go') -connection-mtu $ConnectionMTU -fec $FEC;if($LASTEXITCODE){throw 'MTU budget probe failed'};$budget=$budgetJson|ConvertFrom-Json;$innerMTU=[int]$budget.InnerMTU;$linkMTU=[int]$budget.LinkPlaintextMTU;$budget|ConvertTo-Json -Depth 5|Set-Content -LiteralPath(Join-Path $LogDir 'mtu-budget.json') -Encoding utf8
[string]$distro=[string](@(& wsl.exe -l -q|ForEach-Object{$_.Trim([char]0).Trim()}|Where-Object{$_})|Select-Object -First 1);$distro=$distro.Trim([char]0).Trim();if(-not$distro){throw 'no WSL distribution'};& wsl.exe -d $distro -- true;if($LASTEXITCODE){throw "selected WSL distribution unavailable: $distro"}
function WslPath([string]$Path){(& wsl.exe -d $distro -- wslpath -a $Path).Trim()}
$wslAssets=WslPath $LinuxAssets;$wslLog=WslPath $LogDir;$wslServerScript=WslPath(Join-Path $repo 'scripts\wsl_wintun_lane_soak_server.sh');$serverOut=Join-Path $LogDir 'wsl-wrapper.stdout.log';$serverErr=Join-Path $LogDir 'wsl-wrapper.stderr.log'
$serverArgumentLine="-d `"$distro`" -- sudo bash `"$wslServerScript`" `"$wslAssets`" `"$wslLog`" $innerMTU $ConnectionMTU $Lanes $LossPct ${ServerIdleSec}s"
$server=Start-Process -FilePath 'wsl.exe' -ArgumentList $serverArgumentLine -RedirectStandardOutput $serverOut -RedirectStandardError $serverErr -PassThru -NoNewWindow
$qual=$null;$load=$null;$qualifierStopped=$false;$serverStopped=$false
try{
  $serverReady=Join-Path $LogDir 'server-ready.json';Wait-Path $serverReady 90 $server 'WSL server';$serverInfo=Get-Content -LiteralPath $serverReady -Raw|ConvertFrom-Json;$serverIP=[string]$serverInfo.server_ip;$echoIP=[string]$serverInfo.echo_ip;$echoPort=[int]$serverInfo.echo_port
  if([string]$serverInfo.link_idle_timeout-ne"${ServerIdleSec}s"){throw "server link idle mismatch: $($serverInfo.link_idle_timeout)"}
  $underlayLines=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File(Join-Path $BinDir 'windows_faketcp_underlay.ps1') -RemoteIPAddress $serverIP;if($LASTEXITCODE){throw 'pre-connect underlay discovery failed'};$underlayJSON=$underlayLines|Where-Object{$_-match'^\{'}|Select-Object -First 1;if(-not$underlayJSON){throw 'underlay discovery returned no JSON'};$underlay=$underlayJSON|ConvertFrom-Json;if([string]$underlay.packet_device-notmatch'^\\Device\\NPF_\{.+\}$'){throw 'underlay is not a real Npcap NPF device'}
  $profile=[ordered]@{server_ip=$serverIP;server_port=40000;server_name='target.example';route_key='WBD_REALITY_ROUTE_KEY_0123456789abcdef';username='solo';password='shared-password';verify_server=$false;fec=$FEC;if_name=$adapterName;mtu=$ConnectionMTU;route_mode='Full';dns_mode='System';lanes=$Lanes;idle_timeout=0;keepalive=0;lane_rotation_min_seconds=0;lane_rotation_max_seconds=0}
  $profile|ConvertTo-Json -Depth 6|Set-Content -LiteralPath $profilePath -Encoding utf8;Remove-Item -LiteralPath $readyFile,$stopFile -Force -ErrorAction SilentlyContinue
  [string[]]$qualArgs=@('-profile',[string]$profilePath,'-run-for','0','-stop-file',[string]$stopFile,'-ready-file',[string]$readyFile);$qual=Start-Process -FilePath $qualifier -ArgumentList $qualArgs -RedirectStandardOutput $qualOut -RedirectStandardError $qualErr -PassThru -NoNewWindow;Wait-Path $readyFile 120 $qual 'Windows production controller'
  $lease=Get-NetIPAddress -InterfaceAlias $adapterName -AddressFamily IPv4 -ErrorAction Stop|Where-Object{[string]$_.AddressState-eq'Preferred'}|Select-Object -First 1;if(-not$lease){throw 'Wintun lease missing'};$leaseIP=[string]$lease.IPAddress;$beforeStats=Get-NetAdapterStatistics -Name $adapterName
  $qualText=Get-Content -LiteralPath $qualOut -Raw;if($qualText-notmatch'WBD_FAKETCP_WINDOWS_RAW_SYNACK_RX'-or$qualText-notmatch'WBD_WINDOWS_QUALIFY_CONNECTED'){throw 'initial real-Npcap production connection proof missing'}
  $loadResult=Join-Path $LogDir 'pause-resume-result.json';[string[]]$loadArgs=@([string](Join-Path $repo '.github\scripts\windows_game_pause_resume.py'),'--target',"${echoIP}:$echoPort",'--bind',$leaseIP,'--first-duration',"$FirstDurationSec",'--pause-duration',"$PauseDurationSec",'--second-duration',"$SecondDurationSec",'--rate-bps',"$RateBps",'--payload-bytes','1000','--out',$loadResult)
  $load=Start-Process -FilePath 'python' -ArgumentList $loadArgs -RedirectStandardOutput(Join-Path $LogDir 'load.stdout.log') -RedirectStandardError(Join-Path $LogDir 'load.stderr.log') -PassThru -NoNewWindow
  while(-not$load.HasExited){if($qual.HasExited){throw "production controller exited during pause/resume exit=$($qual.ExitCode)"};Start-Sleep -Milliseconds 250};if($load.ExitCode-ne0){throw "pause/resume load exited $($load.ExitCode)"};if(-not(Test-Path -LiteralPath $loadResult)){throw 'pause/resume result missing'};$loadStats=Get-Content -LiteralPath $loadResult -Raw|ConvertFrom-Json
  if([int64]$loadStats.phase1.unique_rx-le0){throw 'phase1 traffic never traversed full path'};if([int64]$loadStats.phase2.unique_rx-le0){throw 'phase2 traffic did not recover after idle close'};if($null-eq$loadStats.phase2_recovery_delay_sec-or[double]$loadStats.phase2_recovery_delay_sec-gt30){throw "phase2 recovery delay too large: $($loadStats.phase2_recovery_delay_sec)"}
  $qualDuring=Get-Content -LiteralPath $qualOut -Raw;$linkDuring=Get-Content -LiteralPath(Join-Path $LogDir 'link-server.log') -Raw
  if($linkDuring-notmatch'WBD_LINK_MUX_SESSION_CLOSE'){throw 'server did not close an idle LINK session during 220s pause'};if($qualDuring-notmatch'WBD_KEEPALIVE_ZERO_DORMANT'){throw 'client did not enter keepalive-zero dormant state'};if($qualDuring-notmatch'WBD_KEEPALIVE_ZERO_WAKE_PASS'){throw 'client did not lazily rebuild on resumed payload'};if($qualDuring-match'WBD_LANE_ROTATION_PASS'){throw 'automatic lane rotation occurred despite 0/0 profile'}
  $afterStats=Get-NetAdapterStatistics -Name $adapterName;$txBytes=[uint64]$afterStats.SentBytes-[uint64]$beforeStats.SentBytes;$rxBytes=[uint64]$afterStats.ReceivedBytes-[uint64]$beforeStats.ReceivedBytes
  New-Item -ItemType File -Force -Path $stopFile|Out-Null;if(-not$qual.WaitForExit(60000)){throw 'production controller did not stop cleanly'};$qualifierStopped=$true;if($qual.ExitCode-ne0){throw "production controller cleanup exited $($qual.ExitCode)"}
  New-Item -ItemType File -Force -Path $serverStop|Out-Null;if(-not$server.WaitForExit(30000)){throw 'WSL server did not stop cleanly'};$serverStopped=$true;if($server.ExitCode-ne0){throw "WSL server exited $($server.ExitCode)"}
  $fecRows=@();foreach($path in @($qualOut,(Join-Path $LogDir 'link-server.log'))){if(Test-Path -LiteralPath $path){foreach($line in (Get-Content -LiteralPath $path)){if($line-match'^WBD_LINK_FEC_DIAG\s+(\{.*\})$'){$fecRows+=($Matches[1]|ConvertFrom-Json)}}}};$fecPeak=0;$fecMax=0;if($FEC-eq'20:20'){if($fecRows.Count-eq0){throw 'FEC diagnostics missing'};foreach($row in $fecRows){$m=[int]$row.decoder.max_blocks;if($m-ne640){throw "unexpected FEC max_blocks=$m"};$fecMax=$m;$fecPeak=[Math]::Max($fecPeak,[int]$row.peak_in_flight)};if($fecPeak-ge640){throw "FEC decoder saturated peak=$fecPeak"}}elseif($fecRows.Count-ne0){throw 'FEC-off emitted FEC diagnostics'}
  $networkEnd=Join-Path $LogDir 'network-end.log';$outerPre=[int64]-1;$outerPost=[int64]-1;$outerPreBytes=[int64]-1;$outerPostBytes=[int64]-1;$inNetem=$false;foreach($line in (Get-Content -LiteralPath $networkEnd)){if($line-match'^\s*(\d+)\s+(\d+)\s+RETURN\s+tcp\b.*\bspt:40000\b'){$outerPre=[int64]$Matches[1];$outerPreBytes=[int64]$Matches[2]};if($line-match'^qdisc netem 30:'){$inNetem=$true;continue};if($inNetem-and$line-match'Sent\s+(\d+)\s+bytes\s+(\d+)\s+pkt'){$outerPostBytes=[int64]$Matches[1];$outerPost=[int64]$Matches[2];$inNetem=$false}};if($outerPre-le0-or$outerPost-lt0){throw 'outer loss accounting missing'};$outerLoss=100.0*($outerPre-$outerPost)/$outerPre;$outerByteLoss=100.0*($outerPreBytes-$outerPostBytes)/$outerPreBytes;if($outerLoss-lt10-or$outerLoss-gt20){throw "outer packet loss out of band: $outerLoss"};if($outerByteLoss-lt10-or$outerByteLoss-gt20){throw "outer byte loss out of band: $outerByteLoss"}
  $logs=Get-ChildItem -LiteralPath $LogDir -File|Where-Object{$_.Name-match'\.(log|txt)$'};$severe=@($logs|Select-String -Pattern 'panic:|fatal error:|queue overflow|firewall.*(?:leak|bypass)|WBD_(?!KEEPALIVE_ZERO_)[A-Z0-9_]+_FAIL' -ErrorAction SilentlyContinue);$severe|ForEach-Object{"$($_.Path):$($_.LineNumber):$($_.Line)"}|Set-Content -LiteralPath(Join-Path $LogDir 'error-scan.log') -Encoding utf8;if($severe.Count){throw "severe error markers found: $($severe.Count)"}
  $summary=[ordered]@{lanes=$Lanes;fec=$FEC;connection_mtu=$ConnectionMTU;link_plaintext_mtu=$linkMTU;inner_mtu=$innerMTU;keepalive_seconds=0;server_link_idle_seconds=$ServerIdleSec;gateway_idle_seconds=420;first_duration_sec=$FirstDurationSec;pause_duration_sec=$PauseDurationSec;second_duration_sec=$SecondDurationSec;rate_bps=$RateBps;configured_random_loss_pct=$LossPct;phase1_sent=[int64]$loadStats.phase1.sent;phase1_rx=[int64]$loadStats.phase1.unique_rx;phase1_loss_pct=[double]$loadStats.phase1.inner_loss_pct;phase2_sent=[int64]$loadStats.phase2.sent;phase2_rx=[int64]$loadStats.phase2.unique_rx;phase2_loss_pct=[double]$loadStats.phase2.inner_loss_pct;phase2_recovery_delay_sec=[double]$loadStats.phase2_recovery_delay_sec;idle_close_markers=([regex]::Matches($linkDuring,'WBD_LINK_MUX_SESSION_CLOSE')).Count;dormant_markers=([regex]::Matches($qualDuring,'WBD_KEEPALIVE_ZERO_DORMANT')).Count;wake_markers=([regex]::Matches($qualDuring,'WBD_KEEPALIVE_ZERO_WAKE_PASS')).Count;wintun_tx_bytes=$txBytes;wintun_rx_bytes=$rxBytes;outer_packet_loss_pct=$outerLoss;outer_byte_loss_pct=$outerByteLoss;fec_samples=$fecRows.Count;fec_max_blocks=$fecMax;fec_peak_in_flight=$fecPeak;severe_error_scan_matches=$severe.Count;npcap_runtime='real'};$summary|ConvertTo-Json -Depth 12|Set-Content -LiteralPath(Join-Path $LogDir 'summary.json') -Encoding utf8
  Write-Output "WBD_WINDOWS_LINUX_KEEPALIVE_SOAK_PASS lanes=$Lanes fec=$FEC recovery_delay_sec=$([Math]::Round([double]$loadStats.phase2_recovery_delay_sec,3)) outer_loss_pct=$([Math]::Round($outerLoss,3))"
}finally{if($load-and-not$load.HasExited){Stop-Process -Id $load.Id -Force -ErrorAction SilentlyContinue};if($qual-and-not$qualifierStopped-and-not$qual.HasExited){New-Item -ItemType File -Force -Path $stopFile -ErrorAction SilentlyContinue|Out-Null;[void]$qual.WaitForExit(10000);if(-not$qual.HasExited){Stop-Process -Id $qual.Id -Force -ErrorAction SilentlyContinue}};if(-not$serverStopped){New-Item -ItemType File -Force -Path $serverStop -ErrorAction SilentlyContinue|Out-Null;if($server-and-not$server.HasExited){[void]$server.WaitForExit(10000);if(-not$server.HasExited){Stop-Process -Id $server.Id -Force -ErrorAction SilentlyContinue}}}}
