param(
 [Parameter(Mandatory=$true)][string]$BinDir,[Parameter(Mandatory=$true)][string]$LinuxAssets,
 [Parameter(Mandatory=$true)][ValidateSet(1,4)][int]$Lanes,[Parameter(Mandatory=$true)][ValidateSet('off','20:20')][string]$FEC,
 [int]$ConnectionMTU=1420,[int]$DurationSec=300,[int]$RateBps=2000000,[int]$LossPct=15,[int]$RotateEverySec=90,
 [Parameter(Mandatory=$true)][string]$LogDir)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
if($ConnectionMTU-le 0-or$DurationSec-le 0-or$RateBps-le 0-or$LossPct-lt 0-or$LossPct-ge 100-or$RotateEverySec-le 0){throw 'invalid soak parameters'}
New-Item -ItemType Directory -Force -Path $LogDir|Out-Null
$BinDir=(Resolve-Path $BinDir).Path;$LinuxAssets=(Resolve-Path $LinuxAssets).Path;$LogDir=(Resolve-Path $LogDir).Path;$repo=(Resolve-Path(Join-Path $PSScriptRoot '..')).Path
$routeState=Join-Path $LogDir 'wintun-route-state.json';$adapterName='WBDSoak'
function Wait-Marker([string]$Path,[string]$Pattern,[int]$Seconds=60){$end=[DateTime]::UtcNow.AddSeconds($Seconds);while([DateTime]::UtcNow-lt$end){if((Test-Path $Path)-and(Select-String -LiteralPath $Path -Pattern $Pattern -Quiet -ErrorAction SilentlyContinue)){return};Start-Sleep -Milliseconds 100};$tail=if(Test-Path $Path){(Get-Content $Path -Tail 80)-join"`n"}else{'<missing>'};throw "marker timeout path=$Path pattern=$Pattern`n$tail"}
function Start-Logged([string]$Name,[string]$Exe,[string[]]$Args){$out=Join-Path $LogDir "$Name.stdout.log";$err=Join-Path $LogDir "$Name.stderr.log";Remove-Item $out,$err -Force -ErrorAction SilentlyContinue;$p=Start-Process -FilePath $Exe -ArgumentList $Args -RedirectStandardOutput $out -RedirectStandardError $err -PassThru -NoNewWindow;[pscustomobject]@{Name=$Name;Process=$p;Out=$out;Err=$err}}
function Stop-Logged($Proc){if($null-ne$Proc){try{if(-not$Proc.Process.HasExited){Stop-Process -Id $Proc.Process.Id -Force -ErrorAction SilentlyContinue}}catch{}}}
$budgetJson=& go run(Join-Path $repo '.github\scripts\mtu_budget.go') -connection-mtu $ConnectionMTU -fec $FEC;if($LASTEXITCODE){throw 'MTU budget probe failed'}
$budget=$budgetJson|ConvertFrom-Json;$innerMTU=[int]$budget.InnerMTU;$linkMTU=[int]$budget.LinkPlaintextMTU;$budget|ConvertTo-Json -Depth 4|Set-Content(Join-Path $LogDir 'mtu-budget.json') -Encoding utf8
Write-Output "WBD_WINTUN_SOAK_MTU_DERIVED connection=$ConnectionMTU fec=$FEC link=$linkMTU inner=$innerMTU"
$distro=@(& wsl.exe -l -q|ForEach-Object{$_.Trim([char]0).Trim()}|Where-Object{$_})|Select-Object -First 1;if(-not$distro){throw 'no WSL distribution'}
function WslPath([string]$p){(& wsl.exe -d $distro -- wslpath -a $p).Trim()}
$wslAssets=WslPath $LinuxAssets;$wslLog=WslPath $LogDir;$wslServerScript=WslPath(Join-Path $repo 'scripts\wsl_wintun_lane_soak_server.sh')
$serverOut=Join-Path $LogDir 'wsl-wrapper.stdout.log';$serverErr=Join-Path $LogDir 'wsl-wrapper.stderr.log'
$server=Start-Process -FilePath 'wsl.exe' -ArgumentList @('-d',$distro,'--','sudo','bash',$wslServerScript,$wslAssets,$wslLog,"$innerMTU","$ConnectionMTU","$Lanes","$LossPct") -RedirectStandardOutput $serverOut -RedirectStandardError $serverErr -PassThru -NoNewWindow
$all=@();$game=$null;$tunProc=$null;$load=$null
try{
 $ready=Join-Path $LogDir 'server-ready.json';$end=[DateTime]::UtcNow.AddSeconds(60);while(-not(Test-Path $ready)){if($server.HasExited){throw "WSL server exited $($server.ExitCode)"};if([DateTime]::UtcNow-ge$end){throw 'WSL readiness timeout'};Start-Sleep -Milliseconds 200}
 $serverInfo=Get-Content $ready -Raw|ConvertFrom-Json;$serverIP=[string]$serverInfo.server_ip;$echoIP=[string]$serverInfo.echo_ip;$echoPort=[int]$serverInfo.echo_port
 $underlayLines=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File(Join-Path $repo 'scripts\windows_faketcp_underlay.ps1') -RemoteIPAddress $serverIP;if($LASTEXITCODE){throw 'underlay discovery failed'}
 $jsonLine=$underlayLines|Where-Object{$_-match'^\{'}|Select-Object -First 1;if(-not$jsonLine){throw 'underlay JSON missing'};$underlay=$jsonLine|ConvertFrom-Json;$underlay|ConvertTo-Json -Depth 4|Set-Content(Join-Path $LogDir 'underlay.json') -Encoding utf8
 Write-Output "WBD_WINDOWS_OUTER_CARRIER_READY remote=$serverIP npcap_scope=faketcp_only"
 $generation=0
 function Start-Lane([int]$LogicalID,[int]$Slot,[int]$Gen){
  $fakePort=45100+$Slot-1;$dtlsPort=46100+$Slot-1;$linkPort=47100+$Slot-1;$sourcePort=51000+($Gen*10)+$LogicalID;if($sourcePort-gt65000){throw 'source port exhausted'}
  $tag="lane-$LogicalID-g$Gen-s$Slot";$ticket=Join-Path $LogDir "$tag.ticket";$tunnel=Join-Path $LogDir "$tag.tunnel.json"
  $fake=Start-Logged "$tag-faketcp"(Join-Path $BinDir 'wbd-faketcp.exe')@('client','--local-udp',"127.0.0.1:$fakePort",'--source',"$($underlay.source_ip):$sourcePort",'--remote',"${serverIP}:40000",'--shadow-recovery','legacy','--packet-device',[string]$underlay.packet_device,'--source-mac',[string]$underlay.source_mac,'--next-hop-mac',[string]$underlay.next_hop_mac,'--reality-server-name','target.example','--reality-route-key','WBD_REALITY_ROUTE_KEY_0123456789abcdef','--reality-username','solo','--reality-password','shared-password','--reality-ticket-out',$ticket,'--reality-installation-id','00112233445566778899aabbccddeeff','--reality-tunnel-config-out',$tunnel,'--reality-verify-server=false','--reality-timeout','30s')
  $script:all+=$fake;Wait-Marker $fake.Out 'WBD_SINGLE_FLOW_BOOTSTRAP_READY.*logical_tunnel=1' 60;Wait-Marker $fake.Out 'READY role=client' 20;Wait-Marker $fake.Out 'WBD_FAKETCP_WINDOWS_RAW_SYNACK_RX' 5
  $ticketValue=(Get-Content $ticket -Raw).Trim();$tun=Get-Content $tunnel -Raw|ConvertFrom-Json
  $dtls=Start-Logged "$tag-dtls"(Join-Path $BinDir 'wbd_dtls_shim.exe')@('client',"$dtlsPort",'127.0.0.1',"$fakePort",'none','none');$script:all+=$dtls;Wait-Marker $dtls.Out 'READY role=client version=DTLSv1.3' 60
  $link=Start-Logged "$tag-link"(Join-Path $BinDir 'wbd-link-proxy.exe')@('-mode','client','-listen',"127.0.0.1:$linkPort",'-dtls',"127.0.0.1:$dtlsPort",'-fec',$FEC,'-mtu',"$linkMTU",'-lanes','1','-keepalive','15s','-demo-reality-ticket',$ticketValue);$script:all+=$link;Wait-Marker $link.Out "WBD_LINK_READY role=client fec=$([regex]::Escape($FEC))" 60
  [pscustomobject]@{ID=$LogicalID;Slot=$Slot;LinkAddr="127.0.0.1:$linkPort";Fake=$fake;DTLS=$dtls;Link=$link;TunnelID=[string]$tun.tunnel_id;Address4=[string]$tun.address4}
 }
 $active=@{};for($i=1;$i-le$Lanes;$i++){$active[$i]=Start-Lane $i $i 0};$sessionIDs=@($active.Values|%{$_.TunnelID}|Select-Object -Unique);$leases=@($active.Values|%{$_.Address4}|Select-Object -Unique);if($sessionIDs.Count-ne1-or$leases.Count-ne1){throw 'initial lanes disagree on tunnel identity'}
 $sessionID=$sessionIDs[0];$leaseCIDR=$leases[0];$leaseIP=$leaseCIDR.Split('/')[0];$laneTargets=1..$Lanes|%{$active[$_].LinkAddr}
 $game=Start-Logged 'game-client'(Join-Path $BinDir 'wbd-game-lane-client.exe')@('-listen','127.0.0.1:47500','-lanes',($laneTargets-join','),'-control','127.0.0.1:47499','-session-id',$sessionID,'-inner-rate-mbps','2');$all+=$game;Wait-Marker $game.Out "WBD_GAME_LANE_CLIENT_READY.*lanes=$Lanes" 30
 $tunProc=Start-Logged 'wbd-tun'(Join-Path $BinDir 'wbd-tun.exe')@('-mode','client','-ifname',$adapterName,'-mtu',"$innerMTU",'-transport','127.0.0.1:47500','-expected-source-ipv4',$leaseIP);Wait-Marker $tunProc.Err "WBD_TUN_READY mode=client ifname=$adapterName mtu=$innerMTU" 30
 $adapter=Get-NetAdapter -Name $adapterName -ErrorAction Stop;&(Join-Path $repo 'scripts\windows_tun_route.ps1') -Action Apply -Mode Split -AdapterAlias $adapterName -TunnelAddress4 $leaseCIDR -Underlay4 $serverIP -Prefix4 "$echoIP/32" -MTU $innerMTU -StatePath $routeState;if($LASTEXITCODE){throw 'Wintun route apply failed'}
 $beforeStats=Get-NetAdapterStatistics -Name $adapterName
 $smoke=[System.Net.Sockets.UdpClient]::new([System.Net.IPEndPoint]::new([System.Net.IPAddress]::Parse($leaseIP),0));try{$smoke.Client.ReceiveTimeout=15000;$payload=[Text.Encoding]::UTF8.GetBytes("WBD_TUN_FULL_CHAIN_SMOKE_$PID");[void]$smoke.Send($payload,$payload.Length,$echoIP,$echoPort);$peer=[Net.IPEndPoint]::new([Net.IPAddress]::Any,0);$reply=$smoke.Receive([ref]$peer);if(-not[Linq.Enumerable]::SequenceEqual([byte[]]$payload,[byte[]]$reply)){throw 'TUN smoke mismatch'}}finally{$smoke.Dispose()}
 Wait-Marker(Join-Path $LogDir 'shared-tun-gateway.log')'WBD_SHARED_RAWIP_RX_FIRST' 15;Wait-Marker(Join-Path $LogDir 'shared-tun-gateway.log')'WBD_SHARED_RAWIP_TX_FIRST' 15;Write-Output "WBD_WINDOWS_WINTUN_FULL_CHAIN_SMOKE_PASS lease=$leaseIP target=${echoIP}:$echoPort"
 function Send-LaneSet([object[]]$Targets){$rows=@();foreach($x in $Targets){$rows+=[ordered]@{id=[int]$x.ID;address=[string]$x.Address}};$body=[ordered]@{op='set';lanes=$rows}|ConvertTo-Json -Compress -Depth 5;$udp=[System.Net.Sockets.UdpClient]::new();try{$udp.Client.ReceiveTimeout=20000;$bytes=[Text.Encoding]::UTF8.GetBytes($body);[void]$udp.Send($bytes,$bytes.Length,'127.0.0.1',47499);$peer=[Net.IPEndPoint]::new([Net.IPAddress]::Any,0);$reply=[Text.Encoding]::UTF8.GetString($udp.Receive([ref]$peer))|ConvertFrom-Json;if(-not$reply.ok){throw 'lane set rejected'}}finally{$udp.Dispose()}}
 $loadResult=Join-Path $LogDir 'load-result.json';$load=Start-Process -FilePath 'python' -ArgumentList @((Join-Path $repo '.github\scripts\windows_game_load.py'),'--target',"${echoIP}:$echoPort",'--bind',$leaseIP,'--duration',"$DurationSec",'--rate-bps',"$RateBps",'--payload-bytes','1000','--out',$loadResult) -RedirectStandardOutput(Join-Path $LogDir 'load.stdout.log') -RedirectStandardError(Join-Path $LogDir 'load.stderr.log') -PassThru -NoNewWindow
 $clock=[Diagnostics.Stopwatch]::StartNew();$rotations=@();$spare=5
 for($r=1;$r-le3;$r++){$target=$r*$RotateEverySec;while($clock.Elapsed.TotalSeconds-lt$target){if($load.HasExited){throw "load exited early $($load.ExitCode)"};Start-Sleep -Milliseconds 100};$id=(($r-1)%$Lanes)+1;$old=$active[$id];$generation++;$begin=$clock.Elapsed.TotalSeconds;$candidate=Start-Lane $id $spare $generation;if($candidate.TunnelID-ne$sessionID-or$candidate.Address4-ne$leaseCIDR){throw 'rotation changed tunnel identity'};$before=(Select-String -LiteralPath $game.Out -Pattern "WBD_GAME_LANE_CLIENT_QUALIFIED lane=$id " -ErrorAction SilentlyContinue).Count;$overlap=@();for($i=1;$i-le$Lanes;$i++){$overlap+=[pscustomobject]@{ID=$i;Address=$active[$i].LinkAddr};if($i-eq$id){$overlap+=[pscustomobject]@{ID=$i;Address=$candidate.LinkAddr}}};Send-LaneSet $overlap;$deadline=[DateTime]::UtcNow.AddSeconds(30);do{Start-Sleep -Milliseconds 100;$nowCount=(Select-String -LiteralPath $game.Out -Pattern "WBD_GAME_LANE_CLIENT_QUALIFIED lane=$id " -ErrorAction SilentlyContinue).Count}while($nowCount-le$before-and[DateTime]::UtcNow-lt$deadline);if($nowCount-le$before){throw "lane $id did not qualify"};$active[$id]=$candidate;$commit=@();for($i=1;$i-le$Lanes;$i++){$commit+=[pscustomobject]@{ID=$i;Address=$active[$i].LinkAddr}};Send-LaneSet $commit;$commitAt=$clock.Elapsed.TotalSeconds;Stop-Logged $old.Link;Stop-Logged $old.DTLS;Stop-Logged $old.Fake;$spare=$old.Slot;$rotations+=[ordered]@{ordinal=$r;lane=$id;scheduled_sec=$target;qualification_sec=($commitAt-$begin)};Write-Output "WBD_WINDOWS_LANE_ROTATION_PASS ordinal=$r lane=$id"}
 $load.WaitForExit();if($load.ExitCode){throw "load failed $($load.ExitCode)"};$loadStats=Get-Content $loadResult -Raw|ConvertFrom-Json;if([int]$loadStats.bad_payload-ne0-or[int]$loadStats.unique_rx-le0){throw 'invalid inner result'};if([double]$loadStats.inner_loss_pct-ge5.0){throw "inner loss too high $($loadStats.inner_loss_pct)%"}
 $afterStats=Get-NetAdapterStatistics -Name $adapterName;$txBytes=[uint64]$afterStats.SentBytes-[uint64]$beforeStats.SentBytes;$rxBytes=[uint64]$afterStats.ReceivedBytes-[uint64]$beforeStats.ReceivedBytes;if($txBytes-le0-or$rxBytes-le0){throw "Wintun not bidirectional tx=$txBytes rx=$rxBytes"};Write-Output "WBD_WINDOWS_WINTUN_BIDIRECTIONAL_PASS tx_bytes=$txBytes rx_bytes=$rxBytes"
 New-Item -ItemType File -Force -Path(Join-Path $LogDir 'stop.server')|Out-Null;if(-not$server.WaitForExit(30000)){throw 'WSL server stop timeout'};if($server.ExitCode){throw "WSL server failed $($server.ExitCode)"}
 $gatewayLog=Join-Path $LogDir 'shared-tun-gateway.log';foreach($m in @('WBD_SHARED_TUN_SESSION_READY','WBD_SHARED_RAWIP_RX_FIRST','WBD_SHARED_RAWIP_TX_FIRST','WBD_SHARED_TUN_SESSION_COUNTERS')){if(-not(Select-String -LiteralPath $gatewayLog -Pattern $m -Quiet)){throw "shared TUN marker missing $m"}}
 $fecRows=@();$linkServer=Join-Path $LogDir 'link-server.log';foreach($line in Get-Content $linkServer){if($line-match'^WBD_LINK_FEC_DIAG\s+(\{.*\})$'){$fecRows+=($Matches[1]|ConvertFrom-Json)}};$fecPeak=0;if($FEC-eq'20:20'){if($fecRows.Count-eq0){throw 'FEC diagnostics missing'};foreach($row in $fecRows){if([int]$row.decoder.max_blocks-ne640){throw 'bad FEC capacity'};$fecPeak=[Math]::Max($fecPeak,[int]$row.peak_in_flight)};if($fecPeak-ge640){throw 'FEC capacity reached'}}elseif($fecRows.Count-ne0){throw 'FEC off emitted diagnostics'}
 $pressurePeak=0;$pressureSamples=0;$fakeProcesses=@($all|Where-Object{$_.Name-like'*faketcp'});if($fakeProcesses.Count-ne($Lanes+3)){throw 'unexpected FakeTCP process count'};foreach($fp in $fakeProcesses){$samples=0;foreach($line in Get-Content $fp.Out){if($line-match'^WBD_FAKETCP_PRESSURE role=client pending=(\d+) peak_pending=(\d+) capacity=(\d+)$'){$pending=[int]$Matches[1];$peak=[int]$Matches[2];$cap=[int]$Matches[3];if($cap-ne4096){throw 'bad FakeTCP capacity'};$samples++;$pressureSamples++;$pressurePeak=[Math]::Max($pressurePeak,[Math]::Max($pending,$peak))}};if($samples-eq0-or$pressurePeak-ge4096){throw "FakeTCP pressure invalid $($fp.Name)"}}
 $net=Get-Content(Join-Path $LogDir 'network-end.log')-Raw;$sent=0;$qdrop=0;foreach($line in($net-split"`n")){if($line-match'Sent\s+\d+\s+bytes\s+(\d+)\s+pkt\s+\(dropped\s+(\d+)'){$sent=[int64]$Matches[1];$qdrop=[int64]$Matches[2]}};$egressLoss=if(($sent+$qdrop)-gt0){100.0*$qdrop/($sent+$qdrop)}else{-1};if($egressLoss-lt10-or$egressLoss-gt20){throw "outer loss out of band $egressLoss"}
 $fatal=@();Get-ChildItem $LogDir -Filter '*.log'|%{$fatal+=Select-String -LiteralPath $_.FullName -Pattern 'panic:|fatal error:|WBD_[A-Z0-9_]+_FAIL' -ErrorAction SilentlyContinue};if($fatal.Count-gt0){throw "fatal markers $($fatal.Count)"}
 $summary=[ordered]@{lanes=$Lanes;fec=$FEC;connection_mtu=$ConnectionMTU;link_plaintext_mtu=$linkMTU;inner_mtu=$innerMTU;lease=$leaseCIDR;duration_sec=$DurationSec;rate_bps=$RateBps;configured_egress_loss_pct=$LossPct;inner_loss_pct=[double]$loadStats.inner_loss_pct;outer_egress_loss_pct=$egressLoss;wintun_tx_bytes=$txBytes;wintun_rx_bytes=$rxBytes;fec_peak_in_flight=$fecPeak;faketcp_peak_pending=$pressurePeak;faketcp_pressure_samples=$pressureSamples;rotations=$rotations;npcap_scope='outer_faketcp_only';application_path='windows_udp_socket>wintun>wbd-tun>game-lane>link>dtls>faketcp>linux_shared_tun>udp_echo'};$summary|ConvertTo-Json -Depth 8|Set-Content(Join-Path $LogDir 'summary.json') -Encoding utf8
 Write-Output "WBD_WINDOWS_LINUX_WINTUN_SOAK_PASS lanes=$Lanes fec=$FEC inner_loss_pct=$($loadStats.inner_loss_pct) outer_egress_loss_pct=$egressLoss wintun_tx=$txBytes wintun_rx=$rxBytes fec_peak=$fecPeak/640 faketcp_pending_peak=$pressurePeak/4096 rotations=3"
}finally{if($load-and-not$load.HasExited){try{Stop-Process -Id $load.Id -Force}catch{}};try{&(Join-Path $repo 'scripts\windows_tun_route.ps1') -Action Cleanup -StatePath $routeState 2>$null|Out-Null}catch{};if($tunProc){Stop-Logged $tunProc};if($game){Stop-Logged $game};foreach($p in@($all)){Stop-Logged $p};try{New-Item -ItemType File -Force -Path(Join-Path $LogDir 'stop.server')|Out-Null}catch{};if($server-and-not$server.HasExited){try{if(-not$server.WaitForExit(10000)){Stop-Process -Id $server.Id -Force}}catch{}}}
