#!/usr/bin/env python3
"""Minimal two-needle private adapter; historical FEC generator untouched.

It updates the integrity receipt to the *actual* generated bytes and records
the verified origin SHA. No parameters, workload budgets, FEC ratios, deadline,
MTU, business source, or sample interpretation may be rewritten here.
"""
import hashlib
import json
from pathlib import Path
import sys

REPLACEMENTS = (
    ('workflow_rel = ".github/workflows/next-fec-simd-ab.yml"',
     'workflow_rel = ".github/workflows/next-crypto-packet-abba.yml"'),
    ('"tools/fec_simd_ab.py",',
     '"tools/crypto_packet_abba.py",'),
)

def adapt(path):
    p=Path(path)
    old=p.read_bytes()
    receipt_path=Path(str(p)+".receipt.json")
    receipt=json.loads(receipt_path.read_text())
    oldsha=hashlib.sha256(old).hexdigest()
    if receipt.get("schema")!="wbd-large-mtu-harness-template/v1" or receipt.get("generated_sha256")!=oldsha:
        raise ValueError("original fixture receipt hash mismatch")
    s=old.decode("utf-8")
    for before,after in REPLACEMENTS:
        if s.count(before)!=1 or after in s:
            raise ValueError("wrong source fixture selector count")
        s=s.replace(before,after)
    new=s.encode()
    receipt["base_fec_simd_generated_sha256"]=oldsha
    receipt["generated_sha256"]=hashlib.sha256(new).hexdigest()
    receipt["adapter"]="crypto-packet-abba-selectors-v1"
    receipt["selectors_changed_only"]=True
    p.write_bytes(new)
    receipt_path.write_text(json.dumps(receipt,indent=2)+"\n")

if __name__=="__main__":
    if len(sys.argv)!=2:raise SystemExit("usage: prepare_crypto_packet_harness.py generated.sh")
    adapt(sys.argv[1])
